from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BookList, BookViewSet, YourModelViewSet

# Create a router for ViewSets
router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename='book_all')
router.register(r'yourmodel', YourModelViewSet, basename='yourmodel')

urlpatterns = [
    # Read-only list of books
    path('books/', BookList.as_view(), name='book-list'),

    # Include all routes generated by the router
    path('', include(router.urls)),
]
